In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('gurgaon_properties.csv')

In [4]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
262,3 BHK Flat in Sector 63A Gurgaon,flat,birla navya,3.15,14632.0,2153.0,Carpet area: 200,3,3,3,others,"Sector 63A Gurgaon, Gurgaon, Haryana",4.0,East,Jun 2024,"['Sector 54 Chowk Metro Station', 'WorldMark G...",Only igbc gold certified luxury property.,"['1 Chimney', '3 AC', 'No Bed', 'No Curtains',...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2149,3 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,3.75,13383.0,2802.0,Super Built up area 2802(260.31 sq.m.)Built Up...,3,3,2,servant room,"Sector 112 Gurgaon, Gurgaon, Haryana",21.0,West,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Experion windchants 2802sqft - 3 bhk servant.\...,"['1 Water Purifier', '1 Exhaust Fan', '5 Geyse...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1728,4 Bedroom House for sale in DLF Phase 3,house,dlf floors phase 3,3.51,12342.0,2844.0,Plot area 316(264.22 sq.m.),4,4,3,"study room,servant room,store room,pooja room","DLF Phase 3, Gurgaon, Haryana",4.0,East,Oct 2023,"['Dlf phase 3 metro station', 'Guru dronachary...",All 4 floors available for sale (3.51 cr. Per ...,"['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
3550,3 BHK Flat in Sector 36 Sohna,flat,signature global park 4,0.82,7585.0,1081.0,Super Built up area 1081(100.43 sq.m.)Carpet a...,3,2,2,not available,"144, Sector 36 Sohna, Gurgaon, Haryana",2.0,NaN,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'The Leaf Mall ...",We need to shift somewhere else,NaN,"['Lift(s)', 'Park']",NaN
333,9 Bedroom House for sale in Subhash Nagar,house,independent,2.50,13888.0,1800.0,Plot area 1800(167.23 sq.m.),9,5,2,pooja room,"Subhash Nagar, Gurgaon, Haryana",1.0,South-East,10+ Year Old,"['Hanuman Mandir', 'Kharbanda Maternity and Nu...",Size of property is 4045 Check out this 9 bhk ...,NaN,['Park'],"['Environment3.5 out of 5', 'Lifestyle4.5 out ..."

In [5]:
df.shape

(3961, 20)

In [6]:
df.duplicated().sum()

0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [8]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [9]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 3 Gurgaon,house,independent,0.80,8155.0,981.0,Plot area 109(91.14 sq.m.),5,4,1,not available,"Sector 3 Gurgaon, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Hanuman Mandir', 'Sharma Hospital Gurgaon', ...",Interested to sell independent house/villa.Pla...,NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
1,4 BHK Flat in Valley View Estate,flat,valley view estate,1.50,8278.0,1812.0,Carpet area: 1812 (168.34 sq.m.),4,4,3+,"study room,servant room,others","Valley View Estate, Gurgaon, Haryana",9.0,North,10+ Year Old,"['HANUMAN MANDIR', 'SHIV MANDIR BALIYAWAS', 'I...",Apartment specifications: \nSize: 1812 sq ft a...,"['7 Fan', '1 Exhaust Fan', '20 Light', 'No AC'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector 88A Gurgaon,flat,godrej oasis,1.00,6896.0,1450.0,Carpet area: 1450 (134.71 sq.m.),2,2,3,study room,"Sector 88A Gurgaon, Gurgaon, Haryana",7.0,NaN,1 to 5 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...",This beautiful 2 bhk flat in sector-88a gurgao...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ..."
3,4 BHK Flat in Sector 111 Gurgaon,flat,puri diplomatic greens,3.50,11864.0,2950.0,Super Built up area 2950(274.06 sq.m.)Built Up...,4,5,3+,servant room,"Sector 111 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Looking for a 4 bhk property for sale in gurga...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
4,2 BHK Flat in Sector 95A Gurgaon,flat,signature the roselia,0.45,7.0,642857.0,Carpet area: 569243 (52884.41 sq.m.),2,2,2,not available,"Sector 95A Gurgaon, Gurgaon, Haryana",2.0,South-West,0 to 1 Year Old,"['Newtown Square Mall', 'Pataudi Road', 'Dwark...","Highly ventilated and trusted builder, spaciou...",NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area4 out of 5', 'Amenities4 out of 5'..."

In [10]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [11]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 3 Gurgaon,house,independent,Sector 3,0.80,8155.0,981.0,Plot area 109(91.14 sq.m.),5,4,1,not available,"Sector 3 Gurgaon, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Hanuman Mandir', 'Sharma Hospital Gurgaon', ...",Interested to sell independent house/villa.Pla...,NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
1,4 BHK Flat in Valley View Estate,flat,valley view estate,Valley View Estate,1.50,8278.0,1812.0,Carpet area: 1812 (168.34 sq.m.),4,4,3+,"study room,servant room,others","Valley View Estate, Gurgaon, Haryana",9.0,North,10+ Year Old,"['HANUMAN MANDIR', 'SHIV MANDIR BALIYAWAS', 'I...",Apartment specifications: \nSize: 1812 sq ft a...,"['7 Fan', '1 Exhaust Fan', '20 Light', 'No AC'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector 88A Gurgaon,flat,godrej oasis,Sector 88A,1.00,6896.0,1450.0,Carpet area: 1450 (134.71 sq.m.),2,2,3,study room,"Sector 88A Gurgaon, Gurgaon, Haryana",7.0,NaN,1 to 5 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...",This beautiful 2 bhk flat in sector-88a gurgao...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ..."
3,4 BHK Flat in Sector 111 Gurgaon,flat,puri diplomatic greens,Sector 111,3.50,11864.0,2950.0,Super Built up area 2950(274.06 sq.m.)Built Up...,4,5,3+,servant room,"Sector 111 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Looking for a 4 bhk property for sale in gurga...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
4,2 BHK Flat in Sector 95A Gurgaon,flat,signature the roselia,Sector 95A,0.45,7.0,642857.0,Carpet area: 569243 (52884.41 sq.m.),2,2,2,not available,"Sector 95A Gurgaon, Gurgaon, Haryana",2.0,South-West,0 to 1 Year Old,"['Newtown Square Mall', 'Pataudi Road', 'Dwark...","Highly ventilated and trusted builder, spaciou...",NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area4 out of 5', 'Amenities4 out of 5'..."

In [12]:
df['sector'] = df['sector'].str.lower()

In [13]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 3 Gurgaon,house,independent,sector 3,0.80,8155.0,981.0,Plot area 109(91.14 sq.m.),5,4,1,not available,"Sector 3 Gurgaon, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Hanuman Mandir', 'Sharma Hospital Gurgaon', ...",Interested to sell independent house/villa.Pla...,NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
1,4 BHK Flat in Valley View Estate,flat,valley view estate,valley view estate,1.50,8278.0,1812.0,Carpet area: 1812 (168.34 sq.m.),4,4,3+,"study room,servant room,others","Valley View Estate, Gurgaon, Haryana",9.0,North,10+ Year Old,"['HANUMAN MANDIR', 'SHIV MANDIR BALIYAWAS', 'I...",Apartment specifications: \nSize: 1812 sq ft a...,"['7 Fan', '1 Exhaust Fan', '20 Light', 'No AC'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector 88A Gurgaon,flat,godrej oasis,sector 88a,1.00,6896.0,1450.0,Carpet area: 1450 (134.71 sq.m.),2,2,3,study room,"Sector 88A Gurgaon, Gurgaon, Haryana",7.0,NaN,1 to 5 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...",This beautiful 2 bhk flat in sector-88a gurgao...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ..."
3,4 BHK Flat in Sector 111 Gurgaon,flat,puri diplomatic greens,sector 111,3.50,11864.0,2950.0,Super Built up area 2950(274.06 sq.m.)Built Up...,4,5,3+,servant room,"Sector 111 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Looking for a 4 bhk property for sale in gurga...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
4,2 BHK Flat in Sector 95A Gurgaon,flat,signature the roselia,sector 95a,0.45,7.0,642857.0,Carpet area: 569243 (52884.41 sq.m.),2,2,2,not available,"Sector 95A Gurgaon, Gurgaon, Haryana",2.0,South-West,0 to 1 Year Old,"['Newtown Square Mall', 'Pataudi Road', 'Dwark...","Highly ventilated and trusted builder, spaciou...",NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area4 out of 5', 'Amenities4 out of 5'..."

In [14]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 37c                                                    53
nirvana country                                               53
sector 70                                                     53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
dlf phase 2                                                   43
sector 113                                                    43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
laxman vihar                                                  27
sector 71                                                     27
sector 54                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
dlf phase 3                                                   22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 110                                                    16
sector 99                                                     16
sushant lok phase 3                                           16
sector 60                                                     15
sector 63                                                     15
sector 14                                                     15
sector 76                                                     14
gwal pahari                                                   14
sector 53                                                     14
dlf phase 5                                                   14
sector 3                                                      14
sector 52                                                     14
sector 1 imt manesar                                          14
rajendra park                                                 14
laxman vihar phase 2                                          13
sector 46                                                     13
sector 36a                                                    13
sector 31                                                     12
sector 50                                                     12
sector 38                                                     12
uppals southend                                               12
sector 39                                                     12
sohna road                                                    12
sector 93                                                     12
sector 47                                                     11
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 7                                                      10
sector 1a imt manesar                                         10
ashok vihar phase 2                                            9
sector 95a                                                     9
sector 4                                                       9
south city 1                                                   9
sector 55                                                      9
palam vihar extension                                          8
sector 43                                                      8
mehrauli  road                                                 8
c block sushant lok phase 1                                    8
sector 59                                                      8
sector 89 a                                                    8
sector 40                                                      8
dwarka expressway                                              8
sector 10a                                                     8
sector 57                                                      8
malibu town                                                    8
sector 51                                                      7
sector 58                                                      7
new colony                                                     7
sector 11                                                      7
surat nagar 1                                                  7
sector 36 sohna                                                7
sector 26                                                      7
mianwali colony                                                7
sector 5                                                       6
jyoti park                                                     6
ashok vihar                                                    6
rajiv nagar                                                    6
sector 1                                                       6
jacobpura                                                      6
new palam vihar                                                5
ansal plaza                                                    5
subhash nagar                                                  5
sector 23a                                                     5
manesar                                                        5
dayanand colony                                                5
chakkarpur                                                     5
sector 2                                                       5
sushant lok phase 2                                            5
sector 80                                                      5
sector 9                                                       5
sector 30                                                      5
greenwood city                                                 5
sector 28                                                      5
sector 105                                                     5
saraswati vihar                                                5
arjun nagar                                                    5
sector 36                                                      4
valley view estate                                             4
garhi harsaru                                                  4
devilal colony                                                 4
shivpuri                                                       4
sector 45                                                      4
sector 12a                                                     4
imt manesar                                                    4
sector 3a                                                      4
krishna colony                                                 4
suncity                                                        4
baldev nagar                                                   4
sector 6                                                       4
shivaji nagar                                                  4
sector 12                                                      4
surya vihar                                                    4
sector 17                                                      4
ravi nagar                                                     4
vishnu garden                                                  4
new                                                            4
adarsh nagar                                                   4
bhondsi                                                        4
madanpuri                                                      4
dharam colony                                                  4
bhim nagar                                                     4
shakti nagar                                                   3
mg road                                                        3
sector 27                                                      3
prem nagar                                                     3
patel nagar                                                    3
maruti kunj                                                    3
sector 15                                                      3
gandhi nagar                                                   3
sector 17a                                                     3
b block sushant lok phase 1                                    3
sector 110 a                                                   3
sector 23                                                      3
sector 8                                                       3
laxmi garden                                                   3
sector 17b                                                     3
sector 88b                                                     3
a block sushant lok phase 1                                    3
sector 73                                                      3
iffco chowk                                                    2
new palam vihar phase 2                                        2
shanti nagar                                                   2
manohar nagar                                                  2
sector 15 part 2                                               2
bhawani enclave                                                2
golf course ext road                                           2
sector 24                                                      2
surat nagar                                                    2
sushant lok                                                    2
samaspur                                                       2
sector-2 sohna                                                 2
faridabad road                                                 2
sheetla colony                                                 2
sohna  road                                                    2
sector-11 sohna                                                2
bissar                                                         2
, delhi ncr                                                    2
surat nagar phase 2                                            2
block a surya vihar                                            2
mayfield garden                                                2
sispal vihar                                                   2
nars                                                           2
lajpat nagar                                                   2
shankar vihar                                                  2
sector 32                                                      2
hira nagar                                                     2
west rajiv nagar                                               2
sector 21                                                      2
rosewood                                                       2
sector 41                                                      2
new basti                                                      2
acharya puri                                                   2
farukhnagar                                                    2
pratap nagar                                                   2
ambience island                                                2
sector 15 part 1                                               2
new palam vihar phase 1                                        2
daulatabad                                                     2
mohan nagar                                                    2
rajiv chowk                                                    2
golf course road                                               2
south city                                                     1
ashok vihar phase 3                                            1
saraswati enclave                                              1
garauli kalan                                                  1
new colony, sector 7                                           1
shivji park colony                                             1
cyber city                                                     1
mahavir pura                                                   1
dhankot                                                        1
carterpuri village                                             1
part 3 sector 5                                                1
v block dlf phase 3                                            1
naharpur rupa                                                  1
godrej aria , sector 79 ,                                      1
lucknow                                                        1
rajiv colony                                                   1
vir nagar                                                      1
tekchand nagar                                                 1
bhimgarh kheri phase 3                                         1
sector-7 hous                                                  1
sector 37b                                                     1
huda saraswati vihar                                           1
kheri                                                          1
block h ashok vihar phase iii extension                        1
kanahi                                                         1
urban estate, sector 5                                         1
sector 13                                                      1
sultanpur                                                      1
pataudi road                                                   1
gopal nagar, garhi ghasita, sonipat                            1
ashok vihar phase i                                            1
alipur                                                         1
sector 5 chowk                                                 1
begampur khatola                                               1
park view                                                      1
sector 17c                                                     1
rattan garden                                                  1
laxmna vihar, phase 2                                          1
civil l                                                        1
sector-5 sohna                                                 1
ravi nager basai road                                          1
sai kunj                                                       1
damdma                                                         1
near nand hospital                                             1
saroop garden rajendra park                                    1
ansal's palam vihar                                            1
sector-35 sohna                                                1
heritage city                                                  1
sec 3 bhim vihar part 1 bhimgher kheri                         1
block g sector-57                                              1
near euro                                                      1
devi lal colony gali no 12 gurgaon nr omkar public school      1
sector 37a                                                     1
bptp                                                           1
near pataudi chowk                                             1
nirvana country pocket h                                       1
jat colony,fazilpur/taj nagar road                             1
om nagar                                                       1
ats marigold                                                   1
anand garden, sector-105                                       1
mahalaxmi garden, rajendra place                               1
old delhi road, opp sector-14                                  1
khandsa                                                        1
hsiidc plot sector 1 imt manesar                               1
sector 42                                                      1
jacobpura near sadar bazar                                     1
hno 13 sagar enclave sura                                      1
udyog vihar phase 1                                            1
laxman vihar, railway road,                                    1
near sector 1 market                                           1
near khandsa road                                              1
sector 9b                                                      1
sector-5 sheetla colony                                        1
bhora kalan                                                    1
sadar bazar                                                    1
g block dlf city phase 1                                       1
sector 21a faridabad                                           1
sector 4 urban estate                                          1
b1 block sector 57                                             1
new jyoti park                                                 1
ram nagar                                                      1
Name: count, dtype: int64

In [15]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [16]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [17]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [18]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [19]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [20]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [21]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [22]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [23]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 90                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 43                      53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 57                      24
sector 112                     24
sector 24                      24
sector 105                     23
sector 14                      23
sector 88a                     23
sector 33                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 3                       20
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
sector 74                      18
sector 63a                     18
gwal pahari                    18
sector 91                      17
sector 62                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 53                      14
sector 1 manesar               14
sector 55                      14
sector 76                      14
sector 52                      14
sector 46                      13
sector 9                       13
sector 36a                     13
sector 6                       13
sector 4 phase 2               13
sector 93                      12
sector 39                      12
sector 31                      12
sohna road road                12
sector 38                      12
sector 3 phase 3 extension     11
sector 9a                      11
sector 41                      11
sector 13                      10
sector 1a manesar              10
sector 3 phase 2                9
sector 45                       9
sector 95a                      9
manesar                         9
c block sector 43               8
sector 8                        8
sector 2 extension              8
dwarka expressway               8
sector 59                       8
sector 89 a                     8
sector 23                       8
sector 40                       8
sector 17                       8
sector 10a                      8
sector 36 sohna road            7
sector 58                       7
sector 51                       7
sector 21                       6
sector 5                        6
sector 1                        6
new sector 2                    5
sector 30                       5
sector 23a                      5
sector 80                       5
sector 12a                      4
sector 3a                       4
new                             4
sector 36                       4
sector 15                       3
sector 73                       3
a block sector 43               3
maruti kunj                     3
sector 27                       3
sector 88b                      3
patel nagar                     3
sector 17a                      3
sector 110 a                    3
sector 17b                      3
b block sector 43               3
Name: count, dtype: int64

In [24]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [25]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [26]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
370,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
1663,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1964,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3505,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [37]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
583,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
838,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2029,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2146,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3333,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."

In [38]:
df.shape

(3803, 21)

In [39]:
df.duplicated().sum()

0

In [40]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 3 Gurgaon,house,independent,sector 3,0.80,8155.0,981.0,Plot area 109(91.14 sq.m.),5,4,1,not available,"Sector 3 Gurgaon, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Hanuman Mandir', 'Sharma Hospital Gurgaon', ...",Interested to sell independent house/villa.Pla...,NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
1,4 BHK Flat in Valley View Estate,flat,valley view estate,gwal pahari,1.50,8278.0,1812.0,Carpet area: 1812 (168.34 sq.m.),4,4,3+,"study room,servant room,others","Valley View Estate, Gurgaon, Haryana",9.0,North,10+ Year Old,"['HANUMAN MANDIR', 'SHIV MANDIR BALIYAWAS', 'I...",Apartment specifications: \nSize: 1812 sq ft a...,"['7 Fan', '1 Exhaust Fan', '20 Light', 'No AC'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector 88A Gurgaon,flat,godrej oasis,sector 88a,1.00,6896.0,1450.0,Carpet area: 1450 (134.71 sq.m.),2,2,3,study room,"Sector 88A Gurgaon, Gurgaon, Haryana",7.0,NaN,1 to 5 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...",This beautiful 2 bhk flat in sector-88a gurgao...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ..."
3,4 BHK Flat in Sector 111 Gurgaon,flat,puri diplomatic greens,sector 111,3.50,11864.0,2950.0,Super Built up area 2950(274.06 sq.m.)Built Up...,4,5,3+,servant room,"Sector 111 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Looking for a 4 bhk property for sale in gurga...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
4,2 BHK Flat in Sector 95A Gurgaon,flat,signature the roselia,sector 95,0.45,7.0,642857.0,Carpet area: 569243 (52884.41 sq.m.),2,2,2,not available,"Sector 95A Gurgaon, Gurgaon, Haryana",2.0,South-West,0 to 1 Year Old,"['Newtown Square Mall', 'Pataudi Road', 'Dwark...","Highly ventilated and trusted builder, spaciou...",NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area4 out of 5', 'Amenities4 out of 5'..."

In [41]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [42]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
3679,flat,signature andour heights,sector 71,0.55,8607.0,639.0,Super Built up area 639(59.37 sq.m.)Built Up a...,2,2,1,not available,7.0,South-East,1 to 5 Year Old,"['Bigbasket SPR 5K DS', 'iON Digital Zone, DPG...","['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Lift(s)', 'Water St..."
3436,house,independent,sector 55,4.60,21296.0,2160.0,Plot area 240(200.67 sq.m.),3,3,3+,"pooja room,servant room,store room",2.0,North,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...","['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
3951,flat,tulip violet,sector 69,1.66,8408.0,1974.0,Super Built up area 1970(183.02 sq.m.),4,4,1,pooja room,12.0,South-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
467,flat,emaar mgf palm terraces,sector 66,4.50,10599.0,4246.0,Super Built up area 3670(340.95 sq.m.),5,5,3+,servant room,11.0,NaN,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Heritage Schoo...","['10 AC', '1 Modular Kitchen', '1 Chimney', 'N...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1652,flat,smart world orchard,sector 61,2.41,14785.0,1630.0,Built Up area: 1630 (151.43 sq.m.)Carpet area:...,3,3,3,not available,2.0,East,Within 3 months,"['Sector 55-56 Metro station', 'Bestech Centra...","['1 Exhaust Fan', '1 Light', '1 Modular Kitche...",NaN

In [43]:
df.duplicated().sum()

122

In [44]:
df.shape

(3803, 17)

In [ ]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [45]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)